### ISSUE TITLE
perl-xml-parser needs to be rebuilt?

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MSYS2-packages#1148]
After you try to use perl-xml-parser you get this error message:
```
$ perl -e "require XML::Parser"
Can't load '/usr/lib/perl5/vendor_perl/auto/XML/Parser/Expat/Expat.dll' for module XML::Parser::Expat: No such file or directory at /usr/lib/perl5/core_perl/DynaLoader.pm line 193.
 at /usr/lib/perl5/vendor_perl/XML/Parser.pm line 18.
Compilation failed in require at /usr/lib/perl5/vendor_perl/XML/Parser.pm line 18.
BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/XML/Parser.pm line 22.
```

After rebuilding locally on the machine and `pacman -U ...` it works just fine.

Maybe it needs to be rebuilt in the repo?

**Comment by revelator** [comment]
i cannot even rebuild it, perl-5.24 seems to be unable to locate its own dll. Reinstalling does not work either :/

**Comment by revelator** [comment]
Fixed it, i had to rebuild all the perl modules though, it seems the change to cygwin ssp also broke a few other packages besides the ones discovered earlier.

I also discovered what might be a bug in one of the perl patches ->

majmin="msys-perl5_${patchlevel}_${subversion}.${so}"
should probably be 
majmin="msys-perl5${patchlevel}_${subversion}.${so}"
since there is no underscore in the dll name.
I tried it with this change and it works fine with all perl modules so it might be correct, but correct me if im wrong.

**Comment by peterbud** [comment]
With the latest perl it is working fine.
