### ISSUE TITLE
Chrome doesn't like msys2 installer

### ISSUE THREAD

**Issue by martell** [Alexpux/MSYS2-packages#137]
@ricardoquesada sent me this today.

![Image of msys2](http://imgdump.nl/hosted/a7325a4a377ad893f05de408ca8f4757.png)

Seems we have a false positive with the installer and google chrome.
Any ideas on how to fix this ?
Do we change something in the exe or contact google ?

**Comment by dragon788** [comment]
This is happening again. Have to go through a Google Webmaster console to request to be unblocked apparently.

**Comment by martell** [comment]
just download the zip and extract it then? :)

**Comment by dragon788** [comment]
I ended up using Firefox which doesn't have Chrome's sometimes overbearing security features. I believe the issues stems from either needing to update it as a safe package in the Google webmaster tools, or properly signing the executable with the description so that Chrome doesn't flag it.

Considering the fact that Chrome is an extremely popular browser and comes highly recommended by technical people to their non-technical friends I would imagine this limits the number of new users since if they were trying to find a way to run a program and it said to get the msys2 package and they were unable to download it they probably wouldn't have the problem solving skills to work around this. Also considering that the zipped files don't appear prominently at the top of the main page I doubt they would be able to locate them. I also doubt that many users are in the habit of running a program that a browser they trust has deemed insecure, but maybe that's not the case considering how many viruses happen on the Windows even with explicit pop-ups warning users.

**Comment by elieux** [comment]
I guess that's not a problem now.
