### ISSUE TITLE
Can't use chroot

### ISSUE THREAD

**Issue by gbschenkel** [Alexpux/MSYS2-packages#1517]
When using chroot against any directory, a error occour:
```
$ chroot myfolder
chroot: failed to run command ‘/usr/bin/bash’: No such file or directory
```
I tried copy the bash.exe to bash but it didn't resolve the problem.

**Comment by StarWolf3000** [comment]
Its failing because the path gets invalid while trying to chroot. Is there an actual need to use chroot on MSYS2? `/usr/bin/bash` does no longer exist in the environment for MSYS2, when you chroot. You would have to symlink or copy `bash.exe` to `myfolder/usr/bin/` directory for it to work, since you're changing the root path.
Another option is to use `mount` with the option `--bind` to re-mount parts of the filesystem hierarchy into another path (the same can be accomplished by adding those bind mount entries in `/etc/fstab`).

**Comment by gbschenkel** [comment]
I was trying to replicate the sctructure of a server inside MSYS2 for create/test some bash scripts. Since I do some work in home too, I was syncronizing this sctructure and scripts with Git, to continue the work after, and use chroot was for that, because the company polices doesn't accept remote connection. Well, I think putting the bash inside /user/bin will resolve my problems. Thanks for your time.
