### ISSUE TITLE
choco upgrade within an msys2 shell fails with .chocolateyPending file access error

### ISSUE THREAD

**Issue by michaelmaguire** [Alexpux/MSYS2-packages#1568]
If I attempt to use `choco upgrade` within an msys2 window, it fails with error:

```
$ choco upgrade nx.cmake
Chocolatey v0.10.5
Upgrading the following packages:
nx.cmake
By upgrading you accept licenses for the packages.

You have nx.cmake v3.10.0 installed. Version 3.13.3 is available based on your source(s).
Progress: Downloading nx.cmake 3.13.3... 100%

nx.cmake v3.13.3
nx.cmake package files upgrade completed. Performing other installation steps.
nx.cmake not upgraded. An error occurred during installation:
 Item has already been added. Key in dictionary: 'TMP'  Key being added: 'tmp'
The process cannot access the file 'C:\ProgramData\chocolatey\lib\nx.cmake\.chocolateyPending' because it is being used by another process.

```

The same `choco upgrade` works fine from a Windows Command Prompt:

```
C:\Users\mmaguir1>choco upgrade nx.cmake
Chocolatey v0.10.5
Upgrading the following packages:
nx.cmake
By upgrading you accept licenses for the packages.
nx.cmake is not installed. Installing...

nx.cmake v3.13.3
nx.cmake package files upgrade completed. Performing other installation steps.
Attempting to perform the InitializeDefaultDrives operation on the 'FileSystem' provider failed.
Downloading nx.cmake
  from 'http://nxrepo.dev.bloomberg.com/choco/std-sw/cmake/cmake-3.13.3-win64-x64.msi'
Progress: 100% - Completed download of C:\Users\mmaguir1\AppData\Local\Temp\5\chocolatey\nx.cmake\3.13.3\cmake-3.13.3-win64-x64.msi (20.85 MB).
Download of cmake-3.13.3-win64-x64.msi (20.85 MB) completed.
Hashes match.
Installing nx.cmake...
nx.cmake has been installed.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The upgrade of nx.cmake was successful.
  Software installed to 'C:\Program Files\CMake\'

Chocolatey upgraded 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

Is that expected?

```
$ pacman --version

 .--.                  Pacman v5.0.1 - libalpm v10.0.1

$ choco --version
0.10.5
```

**Comment by Alexpux** [comment]
@michaelmaguire we not maintain choco

**Comment by michaelmaguire** [comment]
@Alexpux I guess the question is, would you expect choco to work within msys2?

**Comment by Alexpux** [comment]
@michaelmaguire I’m not use Choco myself and will not try it. So if you want to see it working you must do it it work. This is open source and free time project

**Comment by michaelmaguire** [comment]
@Alexpux thanks that's useful information.  As a user and contributor to open source projects, it's helpful to hear back from maintainers in cases like this e.g. 

A) "Oh, yeah, we know about this problem and we have a plan to fix it, see XXX" or 
B) "Oh, this is new, thanks for helping to improve the project by bringing it to our attention" as well as
C) "Oh, yeah, we know about this problem and there's no way these to systems can ever work properly because of YYY" 

Then there's the plan:

1) "We have no plan to work on this"
2) "We'd be happy if you worked on it"
3) "We don't like the idea of this feature and would never accept it into this project"

It sounds like you are category B)-2) on this issue?

**Comment by Alexpux** [comment]
@michaelmaguire I’m not plan to work on this issue but if you will provide the fix I will review it

**Comment by vgavro** [comment]
The problem is with `TEMP/TMP/temp/tmp` environment variables, see 
https://github.com/git-tfs/git-tfs/issues/135
and http://rcmdnk.com/blog/2013/11/22/computer-windows/
Errors causing problem are:
`Item has already been added. Key in dictionary: 'TMP'  Key being added: 'tmp'`
`Item has already been added. Key in dictionary: 'TEMP'  Key being added: 'temp'`

After this errors `choco.exe` keeps `.chocolateyPending` file exclusively opened (and may hang, you may need to kill process afterwards).
Qickfix is `alias choco='env temp= tmp= choco'` or `echo 'unset temp tmp' > /etc/profile.d/uset_temp.sh'`

**Comment by Biswa96** [comment]
Please don't take this as offensive. Why do you use msys2 in chocolatey? Isn't chocolatey itself a package manager?

**Comment by vgavro** [comment]
> Please don't take this as offensive. Why do you use msys2 in chocolatey? Isn't chocolatey itself a package manager?

I'll take it just as question :-) thanks for interest.
I have toolchain scripts written for linux and I need ability to run them on windows for some of my co-workers - msys2 is best choice for it, while it doesn't always have every package I need - but choco may have (android sdk/ndk for example). While i want to have same environment to run package manager - using choco or pacman.
I consider this as choco bug anyway and don't think It should be fixed in msys2, but keeping this information here may help someone with same problems in future.
I know that writing PKGBUILD script is really easy - maybe I'll consider it as an option next time.

**Comment by Biswa96** [comment]
> but choco may have (android sdk/ndk for example).

Doesn't Android Studio update them?

**Comment by 1480c1** [comment]
> I don't use... anything GUI-related in my toolchains,

Is this one of my people? :laughing:
