### ISSUE TITLE
Sourceforge down ?

### ISSUE THREAD

**Issue by elrhk** [Alexpux/MSYS2-packages#168]
![error servor](https://cloud.githubusercontent.com/assets/5838238/6246123/c8df734a-b765-11e4-8b93-436f0890dd04.PNG)
Hello, problems with SourceForge is offline Msys2 not use the other available reposit please ? thanks

**Comment by Alexpux** [comment]
There are no other mirrors for MSYS2. We don't have infrastructure for this.

**Comment by elrhk** [comment]
ok thanks , I will be patient^^

**Comment by maoueh** [comment]
@elrhk Sourceforge should be  back now, have you been able to resolve your problem? If yes this issue can be closed. Otherwise, reading the error message, pacman db files were probably updated with wrong data which render them unusable.

Check out [this thread](http://sourceforge.net/p/msys2/mailman/msys2-users/thread/54DA46A6.5040406%40verizon.net/#msg33393400) from the mailing list for details about why this problem is there and how to solve it.

**Comment by elrhk** [comment]
resolve thanks
