### ISSUE TITLE
git unable to stash

### ISSUE THREAD

**Issue by KrullKorg** [Alexpux/MSYS2-packages#189]
$ git stash
fatal: Unable to create '/x/var/www/phalcon/tasi/X:/var/www/phalcon/tasi/.git/index.stash.7804.lock': No such file or directory
Cannot save the current worktree state

**Comment by mingwandroid** [comment]
If you run git from the msys2_shell instead, does it work ok?

**Comment by KrullKorg** [comment]
yes

**Comment by mingwandroid** [comment]
Ok, I'm too busy to investigate further, but I think that strace should be used to make a log in each of these cases and those logs should be compared for differences. It may be that mingw-w64-perl is getting called instead of msys2 perl. procmon would be another good way to see if this is what the difference is.

**Comment by KrullKorg** [comment]
in strace i found

fatal: Unable to create '/home/AndreaZ/msys2/C:/msys2_32/home/AndreaZ/msys2/.git/index.stash.10440.lock': No such file or directory

**Comment by mingwandroid** [comment]
Run under the msys2 shell, not a mingw?? shell.

This is only a workaround of course, so the bug report is valid
