### ISSUE TITLE
Path mangling bugs

### ISSUE THREAD

**Issue by dgud** [Alexpux/MSYS2-packages#355]
The first works in "old" msys but not in msys2:

>cl.exe -nologo -D__WIN32__ -DNT -D_CRT_SECURE_NO_DEPRECATE -MD -c -FoC:/msys64/tmp/tmpobj2980/test.o test.c
test.c
C:\Users\uabdgud\src\otp\test.c : fatal error C1083: Cannot open compiler generated file: 'C:C:/msys64/msys64/tmp/tmpobj2980/test.o': Invalid argument

Ok some invalid path mangling going on so let's try with without C:/msys64 
and you get no mangling...

>cl.exe -nologo -D__WIN32__ -DNT -D_CRT_SECURE_NO_DEPRECATE -MD -c -Fo/tmp/tmpobj2980/test.o test.c
test.c
C:\Users\uabdgud\src\otp\test.c : fatal error C1083: Cannot open compiler generated file: '/tmp/tmpobj2980/test.o': No such file or directory

**Comment by mingwandroid** [comment]
These are not "bugs". Path conversion is implemented as a set of heuristics so sometimes it gets it "wrong" in specific instances. Emulating MSYS's path conversion is also not considered a goal for MSYS2.

In this case, "-FoC:/msys64/tmp/tmpobj2980/test" looks like a Unix style pathlist, for example "/usr/local/bin:/usr/bin".

You can use the `MSYS2_ARG_CONV_EXCL` environment variable to prevent specific instances of path conversion that you don't want to happen, see http://sourceforge.net/p/msys2/wiki/Porting/ for more details.

We would consider a patch from a user to to implement per-application rules so that cl.exe is treated differently. mingw-w64's git.exe has some similar issues. Such a patch must be cleanly implemented though, I'd like to see it reading the exclusion rules from a config file rather than being hard-coded.

**Comment by dgud** [comment]
But these things used to work with msys, so this is a regression from the old behavior, 
which I wanted to point out and this is new project so I can understand some non-backwards comp.

What I want is some _consistency_,  I could understand that it either get converted or not.
As it is now I can not use neither /tmp/file which does not become converted
nor c:/msys64/tmp/file which becomes converted and thus doubles 'C:'  which I believe is a bug.

**Comment by mingwandroid** [comment]
We consider that they "worked" a bug in MSYS. I've explained why MSYS2 considers your input to be a pathlist (because it "looks like" one. It has a ":" in it which is not directly after a *single* drive letter).As I said already, we aren't interested in consistency with MSYS,

I already suggested the workaround and suggested a patch. If you're not interested in either of those then I can't see what else I can do here.

**Comment by dgud** [comment]
I already use the workaround with MSYS2_ARG_CONV_EXCL
But I guess that is non clean/trivial to add in Makefile targets but that was not my problem this time.

Thanks for spelling the path_list out for me :-)  did not get it the first time you wrote it nor when I looked the wiki before posting the bug report. My brain pattern matches what I want first.

What you are saying is that -FoC could be a path, it does not look like one to me :-/
but ok then we are into guessing (or heuristics) and suddenly I can understand your point.

While I'm at it thanks for a great "platform" and giving a hope for working windows development environment.

**Comment by mingwandroid** [comment]
Yeah, heuristics are a tricky business and it can get into the realm of "in my opinion" too. We could code for things that look a bit too strange to be paths, but where does it end and how ugly does it make the path conversion code (and thus explaining it to people)? "Never" and "very" would be my guess.

Thanks for the kind comment.
