### ISSUE TITLE
request: Modify the Windows clipboard in some way? (xclip/xsel)

### ISSUE THREAD

**Issue by trapd00r** [Alexpux/MSYS2-packages#581]
Would it be possible, in one way or another, to from within msys2 modify the Windows clipboard in the same way xclip and xsel can do?

**Comment by maoueh** [comment]
I'm unsure about what `xclip` nor `xsel`, but I usually simply do:

```
$ echo 'Wow, clipboarded!' > /dev/clipboard
$ cat /dev/clipboard
Wow, clipboarded!

# Copy something in Windows uisng Ctrl+C
$ cat /dev/clipboard
# Copied content here
```

**Note**: Don't copy the `cat /dev/clipboard` line, type it directly instead. Otherwise, you will have overwritten clipboard content and you would end up with this:

```
$ cat /dev/clipboard
 cat /dev/clipboard
```

Don't make same mistake I made :D

The special `/dev/clipboard` is like any input/ouput device, so you can pipe it to make some nice stuff like `cat /dev/clipboard | jq '.users[0]'`. 

Maybe it's enough for your use case.

**Comment by trapd00r** [comment]
Oh yeah; I love you! Suddenly my life became that much easier! Cheers man!

**Comment by maoueh** [comment]
Glad I could make someone happy and hope and will help others :D

Regards,
Matt
