### ISSUE TITLE
Can't run shell script

### ISSUE THREAD

**Issue by RomikB** [Alexpux/MSYS2-packages#856]
I clone git repository with 2 shell scripts in to /home/user directory
On linux this scripts have set execution permission but on msys2 only one have this permission.
I can't set execute permission for shell script (chmod is ignored).
So how can I run this script?
Is shell scripts creation unsupported by msys2?

**Comment by elieux** [comment]
Every mount under MSYS2 is configured `noacl` by default. This means that MSYS2 won't read or write permissions (see the [Cygwin user guide](https://cygwin.com/cygwin-ug-net/using.html#mount-table)). Most of the time it "just works", but not always, as you noticed.

Either fix the script so that it begins with `#!`, or remount that part of your filesystem with `acl` enabled.

I'm closing this ticket since there's nothing for us to do, but we can continue to discuss here.

**Comment by RomikB** [comment]
I set #! in the beginning of script. It helps. Thank you.
