### ISSUE TITLE
please add python3.5+ and pip support

### ISSUE THREAD

**Issue by congzhangzh** [Alexpux/MSYS2-packages#889]
As python 3.5+ add async await support, which is very usefull and powerfull, hope the new version will be included in package repo:)

pip is also very needed part, which make python package manage easy:)

**Comment by mingwandroid** [comment]
We have Python 3.5 in `MINGW-packages` and no-one here has been interested enough to update Python in MSYS2-packages to 3.5. If you want it done then go ahead and submit a PR.

I doubt we'll be adding pip anytime soon either for the same reasons, the software in this repository exists mostly as build-tools for building software in `MINGW-packages` so until we cannot build something there due to using Python 3.4 without pip here, that is unlikely to change.

**Comment by yujincheng08** [comment]
Dose mingw-w64-python3 meet your need?

**Comment by lazka** [comment]
msys is at 3.6.2, mingw at 3.6.4 now. I guess that should be new enough.

as @mingwandroid said, if you need pip use the mingw python (mingw-w64-i686-python3-pip). If there is a reason why you can't, open an issue and tell us why.
