### ISSUE TITLE
glog package doesn't seem to work. ( mingw-w64-x86_64-glog 0.3.4.4d391fe-3 )

### ISSUE THREAD

**Issue by Joeppie** [Alexpux/MSYS2-packages#960]
Hello,

I've installed the 64 bit version of mingw/msys2 on 2 seperate devices. 
While I can succesfully make use of many libraries,I cannot get even the simplest code (i.e. just calling the init function) to work with the supplied 64 bit shared library for glog. It compiles fine, but will not run.

As soon as the DLL is loaded, an access violation occurs in libglog.dll. I suspect there is something wrong with the binary version of the library; it cannot seem to be loaded. I checked with Dependency Checker, and have verified that a crash occurs loading the glog DLL. The DLL architecture itself is 64 bit as it should be.

On a side note, and not something msys2 can fix, static linking of glog also seems a no-go as this leads to multiple definition errors, pertaining to the fact that glog itself uses, and has its own definition for stack unwinding.

**Comment by peterbud** [comment]
I believe this can be closed due to no response

**Comment by Joeppie** [comment]
I haven't been in the position to try this, I switched over to developing on Linux. However, not even the simplest program linking to glog would work, with the mentioned  mingw-w64-glog package. I am not sure how wise it is to close this issue??

**Comment by peterbud** [comment]
I think you should include here what and how would you like to link to glog, and what is the exact error/symptom you have, which MSYS shell you are using etc. Without that nobody can help you.

**Comment by analca3** [comment]
Hi! I can confirm this is not working. Very simple example:

```cpp
#include <glog/logging.h>

int main(int argc, char const *argv[]) {
  google::InitGoogleLogging(argv[0]);
  LOG(INFO) << "Hi";
  return 0;
}
```

At runtime a popup displays this message

``he application was unable to start correctly (0xc0000142). Click OK to close the application. `

I have a fresh install of MSYS2 with some libraries working like a charm (sqlite3, yaml-cpp). Can I do anything to get glog working?

Thanks for your work! This system solves all my problem with the Windows machine at office :D .

**Comment by analca3** [comment]
Hi, thanks for your answer. 



> When you wrote:
> 
> > Click OK to close the application.
> 
> Do you mean by double clicking on the built executable from the file explorer?

No, it is only because a popup is displayed. I launch the app using conEmu.

![image](https://user-images.githubusercontent.com/3939991/51907104-cdcbfe00-23bd-11e9-890e-338512ea656b.png)


I have set the PATH variable properly, I think.

![image](https://user-images.githubusercontent.com/3939991/51906955-5ac28780-23bd-11e9-9281-b1418895e9b7.png)

If I launch the app using the Mingw64 environment, it does nothing

![image](https://user-images.githubusercontent.com/3939991/51907026-9bba9c00-23bd-11e9-9b47-40e5a54d8347.png)

> Pls read the [wiki](https://github.com/msys2/msys2/wiki) to understand that either:
> 
> * you need to start the application from the MINGW64 shell/subsystem, like `./myglogtest.exe`
> * Or you need to distribute/copy with your application the necessary depenent dlls, in this case the `libglog.dll ` etc.


I can see that `libglog.dll` is in mingw64/bin, and `libglog.dll.a` in mingw64/lib, and both of them are present in the PATH. Am I missing something?

Thanks for your help!

**Comment by peterbud** [comment]
Your executable has a name `"main.x"`?

**Comment by analca3** [comment]
Having this code 

```cpp
#include <iostream>
#include <glog/logging.h>

int main(int argc, char const *argv[]) {
  google::InitGoogleLogging(argv[0]);
  LOG(INFO) << "Hi Log";
  std::cout << "Hi stdout" << std::endl;
  return 0;
}
```

> Let's try first to make sure the compiled executable is working first from within the MINGW64 shell
> 
> * Pls share what is the result of `echo $PATH`
> * Pls share the command you use to build the minimal glog test application you referred above to

Compiling with ` g++ glog-test.cpp -o glog-test -lglog`, the output is nothing inside Mingw64 environment, as in the previous pic. 

```
$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

```

Thank you!

**Comment by peterbud** [comment]
@analca3 your PATH and your test code is OK.
The problem was that libglog was missing the libunwind dependency. Basically the programs using libglog were able to compile, but they were not working (silently failing).

I have submitted a [PR ](https://github.com/Alexpux/MINGW-packages/pull/4935) which is fixing this. With that fix I was able to make the above code work.
Pls note the following:
* when you launch the glog-test.exe from MINGW64 shell, then by default it puts the logfiles into the directory `/msys64/tmp`.
* when you launch the glog-test.exe from command prompt, then by default it puts the logfiles into the `%APPDATA%\Local\Temp` folder

When Alexpux uploads the new version you can try it out.

**Comment by analca3** [comment]
Thank you for the support! I will try again when the PR merges.

**Comment by peterbud** [comment]
@analca3 the package has been uploaded to the repo
